<a href="https://colab.research.google.com/github/kurvamallesh/Machine-Learning-1/blob/main/GridSearchCV_and_RandomizedSearchCV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:

# importing the dependencies
import numpy as np
import pandas as pd
import sklearn.datasets
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV

#We will be working on the breast cancer dataset

In [3]:

# loading the data from sklearn
breast_cancer_dataset = sklearn.datasets.load_breast_cancer()

In [4]:

# loading the data to a data frame
data_frame = pd.DataFrame(breast_cancer_dataset.data, columns = breast_cancer_dataset.feature_names)

In [5]:

# loading the data to a data frame
data_frame = pd.DataFrame(breast_cancer_dataset.data, columns = breast_cancer_dataset.feature_names)

In [6]:

# print the first 5 rows of the dataframe
data_frame.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [7]:

# adding the 'target' column to the data frame
data_frame['label'] = breast_cancer_dataset.target

In [8]:

# print the first 5 rows of the dataframe
data_frame.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,label
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0

In [9]:

# number of rows and Columns in this dataset
data_frame.shape

(569, 31)

In [10]:

# checking for missing values
data_frame.isnull().sum()

mean radius                0
mean texture               0
mean perimeter             0
mean area                  0
mean smoothness            0
mean compactness           0
mean concavity             0
mean concave points        0
mean symmetry              0
mean fractal dimension     0
radius error               0
texture error              0
perimeter error            0
area error                 0
smoothness error           0
compactness error          0
concavity error            0
concave points error       0
symmetry error             0
fractal dimension error    0
worst radius               0
worst texture              0
worst perimeter            0
worst area                 0
worst smoothness           0
worst compactness          0
worst concavity            0
worst concave points       0
worst symmetry             0
worst fractal dimension    0
label                      0
dtype: int64

In [11]:

# checking the distribution of Target Varibale
data_frame['label'].value_counts()

1    357
0    212
Name: label, dtype: int64

In [12]:

X = data_frame.drop(columns='label', axis=1)
Y = data_frame['label']

In [13]:

 X = np.asarray(X)
 Y = np.asarray(Y)


# **GridSearchCV**

GridsearchCV is used to determining the best parameters for our model

In [14]:
#loading the svc model
model=SVC()

In [15]:
#hyperparameters
parameters={
    'kernel':['linear','poly','rgf','sigmoid'],
    'C':[1,5,10,20]
}

In [16]:
#grid searchCV
classifier=GridSearchCV(model,parameters, cv=5)

In [18]:
#fitting the data to our model
classifier.fit(X,Y)

/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning:
20 fits failed out of a total of 80.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
20 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/svm/_base.py", line 255, in fit
    fit(X, y, sample_weight, solver_type, kernel, random_seed=seed)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/svm/_base.py", line 315, in _dense_fit
    ) = libsvm.fit(
  File "sklearn/svm/_libsvm.pyx", line 173, in sklearn.svm._libsvm.fit
ValueError: 'rgf' is not in list

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_search.py:969: UserWarning: One or more of the test scores are non-finite: [0.94553641 0.90866325        nan 0.46044093 0.95081509 0.92272939
        nan 0.41117839 0.95256948 0.920975          nan 0.40239093
 0.9490607  0.91922062        nan 0.39886664]
  warnings.warn(

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [1, 5, 10, 20],
                         'kernel': ['linear', 'poly', 'rgf', 'sigmoid']})

In [19]:
classifier.cv_results_

{'mean_fit_time': array([1.24572754e+00, 3.35111618e-03, 6.42871857e-04, 1.27439022e-02,
        2.54310498e+00, 3.07865143e-03, 5.47504425e-04, 1.12776279e-02,
        5.15086069e+00, 3.62286568e-03, 6.43301010e-04, 1.07853889e-02,
        6.04271812e+00, 3.25322151e-03, 4.95672226e-04, 1.07212543e-02]),
 'std_fit_time': array([4.87256106e-01, 3.28551204e-04, 2.21273847e-04, 2.40191562e-04,
        5.10807556e-01, 4.58984669e-04, 6.57159803e-05, 3.38582904e-04,
        2.01920655e+00, 5.92032182e-04, 1.69498500e-04, 4.80486599e-04,
        1.93927016e+00, 1.03407060e-04, 1.45361053e-05, 5.45142033e-04]),
 'mean_score_time': array([0.00075116, 0.00092626, 0.        , 0.00306916, 0.00067949,
        0.00077882, 0.        , 0.00271559, 0.00218067, 0.00082545,
        0.        , 0.00253992, 0.00064969, 0.00063882, 0.        ,
        0.00254383]),
 'std_score_time': array([5.99916483e-05, 1.50422588e-04, 0.00000000e+00, 7.28283493e-05,
        1.64221776e-05, 1.11509427e-04, 0.00000000e+00, 6.70420157e-05,
        2.75492004e-03, 1.87662861e-04, 0.00000000e+00, 4.89715244e-05,
        2.80374572e-05, 3.28064658e-05, 0.00000000e+00, 5.51312433e-05]),
 'param_C': masked_array(data=[1, 1, 1, 1, 5, 5, 5, 5, 10, 10, 10, 10, 20, 20, 20, 20],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['linear', 'poly', 'rgf', 'sigmoid', 'linear', 'poly',
                    'rgf', 'sigmoid', 'linear', 'poly', 'rgf', 'sigmoid',
                    'linear', 'poly', 'rgf', 'sigmoid'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'linear'},
  {'C': 1, 'kernel': 'poly'},
  {'C': 1, 'kernel': 'rgf'},
  {'C': 1, 'kernel': 'sigmoid'},
  {'C': 5, 'kernel': 'linear'},
  {'C': 5, 'kernel': 'poly'},
  {'C': 5, 'kernel': 'rgf'},
  {'C': 5, 'kernel': 'sigmoid'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'poly'},
  {'C': 10, 'kernel': 'rgf'},
  {'C': 10, 'kernel': 'sigmoid'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'poly'},
  {'C': 20, 'kernel': 'rgf'},
  {'C': 20, 'kernel': 'sigmoid'}],
 'split0_test_score': array([0.94736842, 0.84210526,        nan, 0.54385965, 0.94736842,
        0.88596491,        nan, 0.49122807, 0.93859649, 0.88596491,
               nan, 0.48245614, 0.92982456, 0.87719298,        nan,
        0.47368421]),
 'split1_test_score': array([0.92982456, 0.88596491,        nan, 0.45614035, 0.93859649,
        0.9122807 ,        nan, 0.42105263, 0.93859649, 0.92105263,
               nan, 0.40350877, 0.95614035, 0.92105263,        nan,
        0.40350877]),
 'split2_test_score': array([0.97368421, 0.92982456,        nan, 0.46491228, 0.97368421,
        0.92105263,        nan, 0.42105263, 0.97368421, 0.90350877,
               nan, 0.42105263, 0.95614035, 0.90350877,        nan,
        0.42105263]),
 'split3_test_score': array([0.92105263, 0.94736842,        nan, 0.38596491, 0.92982456,
        0.93859649,        nan, 0.35087719, 0.94736842, 0.93859649,
               nan, 0.34210526, 0.93859649, 0.93859649,        nan,
        0.34210526]),
 'split4_test_score': array([0.95575221, 0.9380531 ,        nan, 0.45132743, 0.96460177,
        0.95575221,        nan, 0.37168142, 0.96460177, 0.95575221,
               nan, 0.36283186, 0.96460177, 0.95575221,        nan,
        0.3539823 ]),
 'mean_test_score': array([0.94553641, 0.90866325,        nan, 0.46044093, 0.95081509,
        0.92272939,        nan, 0.41117839, 0.95256948, 0.920975  ,
               nan, 0.40239093, 0.9490607 , 0.91922062,        nan,
        0.39886664]),
 'std_test_score': array([0.01868869, 0.03938232,        nan, 0.05025317, 0.01621632,
        0.02368918,        nan, 0.04857818, 0.01419963, 0.02470123,
               nan, 0.0489065 , 0.01281637, 0.02730027,        nan,
        0.0476401 ]),
 'rank_test_score': array([ 4,  8, 13,  9,  2,  5, 14, 10,  1,  6, 15, 11,  3,  7, 16, 12],
       dtype=int32)}

In [20]:
#best parameters

best_parameters=classifier.best_params_

print(best_parameters)

{'C': 10, 'kernel': 'linear'}

In [22]:
#highest accuracy

highest_accuracy=classifier.best_score_
print(highest_accuracy)

0.9525694767893185

In [23]:
#loading the results to pandas dataframe
result=pd.DataFrame(classifier.cv_results_)

In [24]:
result.head()

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,1.245728,0.487256,0.000751,0.000060,1,linear,"{'C': 1, 'kernel': 'linear'}",0.947368,0.929825,0.973684,0.921053,0.955752,0.945536,0.018689,4
1,0.003351,0.000329,0.000926,0.000150,1,poly,"{'C': 1, 'kernel': 'poly'}",0.842105,0.885965,0.929825,0.947368,0.938053,0.908663,0.039382,8
2,0.000643,0.000221,0.000000,0.000000,1,rgf,"{'C': 1, 'kernel': 'rgf'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
3,0.012744,0.000240,0.003069,0.000073,1,sigmoid,"{'C': 1, 'kernel': 'sigmoid'}",0.543860,0.456140,0.464912,0.385965,0.451327,0.460441,0.050253,9
4,2.543105,0.510808,0.000679,0.000016,5,linear,"{'C': 5, 'kernel': 'linear'}",0.947368,0.938596,0.973684,0.929825,0.964602,0.950815,0.016216,2

In [26]:
grid_search_result=result[['param_C','param_kernel','mean_test_score']]

In [27]:
grid_search_result

   param_C param_kernel  mean_test_score
0        1       linear         0.945536
1        1         poly         0.908663
2        1          rgf              NaN
3        1      sigmoid         0.460441
4        5       linear         0.950815
5        5         poly         0.922729
6        5          rgf              NaN
7        5      sigmoid         0.411178
8       10       linear         0.952569
9       10         poly         0.920975
10      10          rgf              NaN
11      10      sigmoid         0.402391
12      20       linear         0.949061
13      20         poly         0.919221
14      20          rgf              NaN
15      20      sigmoid         0.398867

The highest Accuracy=95.25%

Best parameters ={'C': 10, 'kernel': 'linear'}

#**RandomisedSearchCV**

In [28]:
#loading the SVC model
model=SVC()

In [29]:
#hyperparameters
parameters={
    'kernel':['linear','poly','rgf','sigmoid'],
    'C':[1,5,10,20]
}

In [30]:
#Randomized search 
classifier=RandomizedSearchCV(model,parameters,cv=5)

In [31]:
#fitting the data into our model
classifier.fit(X,Y)

/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning:
15 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/svm/_base.py", line 255, in fit
    fit(X, y, sample_weight, solver_type, kernel, random_seed=seed)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/svm/_base.py", line 315, in _dense_fit
    ) = libsvm.fit(
  File "sklearn/svm/_libsvm.pyx", line 173, in sklearn.svm._libsvm.fit
ValueError: 'rgf' is not in list

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_search.py:969: UserWarning: One or more of the test scores are non-finite: [0.92272939 0.94553641 0.40239093        nan 0.95081509 0.41117839
 0.46044093 0.91922062        nan        nan]
  warnings.warn(

RandomizedSearchCV(cv=5, estimator=SVC(),
                   param_distributions={'C': [1, 5, 10, 20],
                                        'kernel': ['linear', 'poly', 'rgf',
                                                   'sigmoid']})

In [32]:
classifier.cv_results_

{'mean_fit_time': array([4.16193008e-03, 1.22769308e+00, 1.13519192e-02, 5.48648834e-04,
        2.50976849e+00, 1.10594273e-02, 1.15388393e-02, 3.27439308e-03,
        5.07783890e-04, 4.67872620e-04]),
 'std_fit_time': array([1.23575151e-03, 4.93147772e-01, 4.43363426e-04, 5.66201510e-05,
        5.13443601e-01, 3.90771167e-04, 3.13918296e-04, 9.24062432e-05,
        3.82572012e-05, 1.34410575e-05]),
 'mean_score_time': array([0.00089521, 0.0007812 , 0.00284925, 0.        , 0.00065618,
        0.00270333, 0.00288124, 0.00071173, 0.        , 0.        ]),
 'std_score_time': array([2.35923992e-04, 1.76457429e-04, 2.88567201e-04, 0.00000000e+00,
        4.92052050e-05, 2.12358645e-04, 6.01825167e-05, 2.54741745e-05,
        0.00000000e+00, 0.00000000e+00]),
 'param_kernel': masked_array(data=['poly', 'linear', 'sigmoid', 'rgf', 'linear',
                    'sigmoid', 'sigmoid', 'poly', 'rgf', 'rgf'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False],
        fill_value='?',
             dtype=object),
 'param_C': masked_array(data=[5, 1, 10, 10, 5, 5, 1, 20, 20, 5],
              mask=[False, False, False, False, False, False, False, False,
                    False, False],
        fill_value='?',
             dtype=object),
 'params': [{'kernel': 'poly', 'C': 5},
  {'kernel': 'linear', 'C': 1},
  {'kernel': 'sigmoid', 'C': 10},
  {'kernel': 'rgf', 'C': 10},
  {'kernel': 'linear', 'C': 5},
  {'kernel': 'sigmoid', 'C': 5},
  {'kernel': 'sigmoid', 'C': 1},
  {'kernel': 'poly', 'C': 20},
  {'kernel': 'rgf', 'C': 20},
  {'kernel': 'rgf', 'C': 5}],
 'split0_test_score': array([0.88596491, 0.94736842, 0.48245614,        nan, 0.94736842,
        0.49122807, 0.54385965, 0.87719298,        nan,        nan]),
 'split1_test_score': array([0.9122807 , 0.92982456, 0.40350877,        nan, 0.93859649,
        0.42105263, 0.45614035, 0.92105263,        nan,        nan]),
 'split2_test_score': array([0.92105263, 0.97368421, 0.42105263,        nan, 0.97368421,
        0.42105263, 0.46491228, 0.90350877,        nan,        nan]),
 'split3_test_score': array([0.93859649, 0.92105263, 0.34210526,        nan, 0.92982456,
        0.35087719, 0.38596491, 0.93859649,        nan,        nan]),
 'split4_test_score': array([0.95575221, 0.95575221, 0.36283186,        nan, 0.96460177,
        0.37168142, 0.45132743, 0.95575221,        nan,        nan]),
 'mean_test_score': array([0.92272939, 0.94553641, 0.40239093,        nan, 0.95081509,
        0.41117839, 0.46044093, 0.91922062,        nan,        nan]),
 'std_test_score': array([0.02368918, 0.01868869, 0.0489065 ,        nan, 0.01621632,
        0.04857818, 0.05025317, 0.02730027,        nan,        nan]),
 'rank_test_score': array([ 3,  2,  7,  8,  1,  6,  5,  4,  9, 10], dtype=int32)}

In [33]:
#best parameters

best_parameters=classifier.best_params_
print(best_parameters)

{'kernel': 'linear', 'C': 5}

In [34]:
#highest accuracy

highest_accuracy=classifier.best_score_
print(highest_accuracy)

0.9508150908244062

In [37]:
#loading the results to pandas dataframe
randomized_result=pd.DataFrame(classifier.cv_results_)

In [38]:
randomized_result.head()

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.004162,0.001236,0.000895,0.000236,poly,5,"{'kernel': 'poly', 'C': 5}",0.885965,0.912281,0.921053,0.938596,0.955752,0.922729,0.023689,3
1,1.227693,0.493148,0.000781,0.000176,linear,1,"{'kernel': 'linear', 'C': 1}",0.947368,0.929825,0.973684,0.921053,0.955752,0.945536,0.018689,2
2,0.011352,0.000443,0.002849,0.000289,sigmoid,10,"{'kernel': 'sigmoid', 'C': 10}",0.482456,0.403509,0.421053,0.342105,0.362832,0.402391,0.048906,7
3,0.000549,0.000057,0.000000,0.000000,rgf,10,"{'kernel': 'rgf', 'C': 10}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,8
4,2.509768,0.513444,0.000656,0.000049,linear,5,"{'kernel': 'linear', 'C': 5}",0.947368,0.938596,0.973684,0.929825,0.964602,0.950815,0.016216,1

In [39]:
randomized_search_result=result[['param_C','param_kernel','mean_test_score']]

In [40]:
randomized_search_result

  param_C param_kernel  mean_test_score
0       5         poly         0.922729
1       1       linear         0.945536
2      10      sigmoid         0.402391
3      10          rgf              NaN
4       5       linear         0.950815
5       5      sigmoid         0.411178
6       1      sigmoid         0.460441
7      20         poly         0.919221
8      20          rgf              NaN
9       5          rgf              NaN

Highest Accuracy=95.08%

Best Parameters={'kernel': 'linear', 'C': 5}